* תיאוריה שמסבירה למה יש קיום של משהו כלל
השאלה התחילה בכך שקשה לאדם מערבי מודרני לתפוס שהישות הראשונית היא אלוקים, ישות רוחנית כל יכולה, שלפני שבראה את העולם הייתה רק היא בצורת אחדות פשוטה. למה בעצם כל כך קשה לתפוס את זה? כשחושבים על ראשית היקום, הנטייה הראשונית היא להתחיל מכלום. שהרי, אם יש משהו הוא צריך סיבה, וכיון שמדובר בראשית הקיום לא יכולה להיות סיבה.
ישנן שתי בעיות יסודיות בחשיבה זו:
1. מכלום לא יכול לצאת משהו. גם הניסיון של הפיזיקאים להגיד שחומר ואנטי חומר שמאיינים זה את זה אכן יכולים לצאת מכלום, מניחים שיש חוקי פיזיקה שמאפשרים קיום של חומר ואנטי חומר, אך זה אינו כלום. גם חוקים הם משהו, ולכן גם צריכים סיבה, לכן המוטיבציה הראשונית להגיד שהיקום יצא מכלום נופלת.
2. לא יכולה להיות תיאוריה או הסבר שתומך בטענה שהיקום התחיל מכלום בהגדרה, כיון שאין כלום, אין גם תיאוריה שתסביר אותו..

אך, עדיין זה קשה לעיכול, כי למרות אפילו שאנחנו מבינים בגלל שתי הבעיות לעיל שלא יכול להיות שהיקום התחיל מכלום, אין לנו שום תיאוריה שתסביר למה היקום כן התחיל ממשהו, יהיה מה שיהיה.
אך בעצם, מהי תיאוריה? תיאוריה היא גם ישות..

